name: Update Kataeb RSS Feed

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4 # تحديث لنسخة v4 المتوافقة مع Node الجديد

    - name: Set up Python
      uses: actions/setup-python@v5 # تحديث لنسخة v5 المتوافقة مع Node الجديد
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 feedgen

    - name: Run Scraper Script
      run: python scraper.py

    - name: Commit and Push RSS file
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add kataeb_feed.xml
        git commit -m "Auto-update RSS feed [skip ci]" || exit 0
        git push
